### ISSUE TITLE
shortcuts for accessing FHIRPrimitive values?

### ISSUE THREAD

**Issue by xinsight** [apple/FHIRModels#1]
Hi,

I'm interested in using this library to parse FHIR json, but I'm finding it as difficult to work with `FHIRModels` than just parsing the JSON manually.

Here's my setup:

```
// json dictionary
guard let dict = try? JSONSerialization.jsonObject(with: data, options: []) as? [String: Any] else {
    fatalError("unable to create JSON dict")
}

// FHIRModel
guard let observation = try? JSONDecoder().decode(ModelsDSTU2.Observation.self, from: data) else {
    fatalError("unable to create observation")
}
```

Getting a resource id:

```
// json
guard let id = json["id"] as? String else {
    fatalError("resource missing id")
}

// FHIRModel
guard let id = observation.id?.value?.string else {
   fatalError("resource missing id")
}
```

Extracting a value from an extension:

```
let uuid: String?

// json
if let extensions = json["extension"] as? [JSON] {
    extensions.forEach { extension_fhir in
        if extension_fhir["url"] as? String == Extension.healthKitUUID, let uuidString = extension_fhir["valueId"] as? String {
            uuid = uuidString
    }
}

// FHIRModel
if let `extension` = observation.`extension`?.first(where: { $0.url.value?.url.absoluteString == Extension.healthKitUUID }) {
    switch `extension`.value { // can we avoid the switch statement?
    case let .id(fhirString):
        uuid = fhirString.value?.string
    default:
        fatalError()
    }
}
```

Any suggestions on how this could be improved?

Also, a few more examples of parsing in the README would be helpful. I'm still trying to figure out how to get a `Date` from `FHIRDateTime`!

**Comment by p2-apple** [comment]
Hey Jason!

Totally acknowledge that in the cases above it seems even more cumbersome to use FHIRModels than just working with dictionaries or writing your own, concise codables. The benefit of using FHIRModell arises once you dive a little bit deeper. We do plan to add more documentation, but for now:

### Decoding the resource

The dictionary will just tell you that _something_ is not a JSON dictionary, whereas FHIRModels will tell you if the data is not a valid `Observation` resource (in this case) and where exactly the problem lies.

You will also find it easier to get at the resources from a `Bundle`, e.g. from a search:

```swift
let bundle = try JSONDecoder().decode(ModelsDSTU2.Bundle.self, from: data)
let observations = bundle.entry?.compactMap {
    $0.resource?.get(if: ModelsDSTU2.Observation.self)
}
// observations is an array of `Observation` resources
```

### Resource ID

If you just keep operating with using the id as a type of `FHIRPrimitive<FHIRString>`, you have the benefit of not losing e.g. extensions on the ID and in many places you can use it just like a String. So, it depends what you want to do with it.

```swift
if observation.id == "1" {
    // ...
}
```

### Extensions

We plan to add convenience methods. The switch over the enum is there to ensure you don't have `valueString` and another `value[x]` field, which would be invalid. For now you can shorten the code you have to:

```swift
if let `extension` = observation.extension?.first(where: { $0.url.value == "..." }) {
    if case .string(let uuid) = `extension`.value {
        // "uuid" is a `FHIRPrimitive<FHIRString>`
    }
}
```

### Date ↔︎ FHIRDateTime Conversion

Planned!

**Comment by xinsight** [comment]
Hi Pascal,

Thanks for the additional examples and explanations. Using an enum to ensure there is only value is clever, and the `if case` shortcut is handy. Looking forward to playing around with this some more!

Regards,

:jason

**Comment by p2-apple** [comment]
Added a tiny bit more about primitives to the README, but still working on improvements in this area.

**Comment by p2-apple** [comment]
I think this is somewhat done in our new "How To" section: https://github.com/apple/FHIRModels/blob/main/HowTo/README.md
